server:
  address: 2002
  model: debug
  # model: release

db:
  dialects: mysql
  host: 127.0.0.1
  port: 3306
  dbname: go-rbac
  username: ohayo
  password: 123456
  charset: utf8
  # 最大空闲数
  maxIdle: 50
  # 最大连接数
  maxConn: 150

redis:
  address: 127.0.0.1:6379
  password:

imgUpload:
  uploadDir: /go-admin/upload
  imgHost: http://127.0.0.1:2002

log:
  path: ./log
  name: sys
  model: console
  # model: file