definitions:
  entity.AddSysRoleDto:
    properties:
      description:
        type: string
      roleKey:
        type: string
      roleName:
        type: string
      status:
        type: integer
    type: object
  entity.DelSysPostDto:
    properties:
      ids:
        items:
          type: integer
        type: array
    type: object
  entity.LoginDto:
    properties:
      idKey:
        description: uuid
        type: string
      image:
        description: 验证码
        maxLength: 6
        minLength: 4
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - idKey
    - image
    - password
    - username
    type: object
  entity.RoleMenu:
    properties:
      id:
        type: integer
      menuIds:
        items:
          type: integer
        type: array
    required:
    - id
    - menuIds
    type: object
  entity.SysDept:
    properties:
      children:
        description: -表示不和数据库字段相关联
        items:
          $ref: '#/definitions/entity.SysDept'
        type: array
      createTime:
        $ref: '#/definitions/util.HTime'
      deptName:
        type: string
      deptStatus:
        type: integer
      deptType:
        type: integer
      id:
        type: integer
      parentId:
        type: integer
    type: object
  entity.SysDeptDto:
    properties:
      id:
        type: integer
    type: object
  entity.SysMenu:
    properties:
      children:
        items:
          $ref: '#/definitions/entity.SysMenu'
        type: array
      createTime:
        $ref: '#/definitions/util.HTime'
      icon:
        type: string
      id:
        type: integer
      menuName:
        type: string
      menuStatus:
        type: integer
      menuType:
        type: integer
      parentId:
        type: integer
      sort:
        type: integer
      url:
        type: string
      value:
        type: string
    type: object
  entity.SysMenuIdDto:
    properties:
      id:
        type: integer
    type: object
  entity.SysPost:
    properties:
      createTime:
        $ref: '#/definitions/util.HTime'
      id:
        type: integer
      postCode:
        type: string
      postName:
        type: string
      postStatus:
        type: integer
      remark:
        type: string
    type: object
  entity.SysPostIdDto:
    properties:
      id:
        type: integer
    type: object
  entity.SysRoleIdDto:
    properties:
      id:
        type: integer
    type: object
  entity.UpdateSysPostStatusDto:
    properties:
      id:
        type: integer
      postStatus:
        type: integer
    type: object
  entity.UpdateSysRoleDto:
    properties:
      description:
        type: string
      id:
        type: integer
      roleKey:
        type: string
      roleName:
        type: string
      status:
        type: integer
    type: object
  entity.UpdateSysRoleStatusDto:
    properties:
      id:
        type: integer
      status:
        type: integer
    type: object
  result.Result:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  util.HTime:
    properties:
      time.Time:
        type: string
    type: object
info:
  contact: {}
  title: 管理后台接口
  version: "0.1"
paths:
  /api/captcha:
    get:
      description: 验证码接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 验证码接口
  /api/dept/add:
    post:
      description: 新增部门
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysDept'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 新增部门
  /api/dept/delete:
    delete:
      description: 根据部门id删除
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysDeptDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据部门id删除
  /api/dept/info:
    get:
      description: 根据部门id查询
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据部门id查询
  /api/dept/list:
    get:
      description: 查询部门列表
      parameters:
      - description: 部门名称
        in: query
        name: deptName
        type: string
      - description: 部门状态
        in: query
        name: deptStatus
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 查询部门列表
  /api/dept/update:
    put:
      description: 编辑部门
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysDept'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 编辑部门
  /api/dept/vo/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 获取部门下拉列表
  /api/login:
    post:
      description: 用户登录接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 用户登录接口
  /api/menu/add:
    post:
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysMenu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 创建菜单
  /api/menu/delete:
    delete:
      description: 删除菜单
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysMenuIdDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 删除菜单
  /api/menu/info:
    get:
      description: 根据菜单id查询
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据菜单id查询
  /api/menu/list:
    get:
      description: 获取菜单列表
      parameters:
      - description: 菜单名称
        in: query
        name: menuName
        type: string
      - description: 菜单状态
        in: query
        name: menuStatus
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 获取菜单列表
  /api/menu/update:
    put:
      description: 编辑菜单
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysMenu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 编辑菜单
  /api/menu/vo/list:
    get:
      description: 查询菜单下拉列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 查询菜单下拉列表
  /api/post/add:
    post:
      description: 新增岗位接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 新增岗位接口
  /api/post/batch/delete:
    delete:
      description: 批量删除岗位
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.DelSysPostDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 批量删除岗位
  /api/post/delete:
    delete:
      description: 根据岗位id删除
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysPostIdDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据岗位id删除
  /api/post/info:
    get:
      description: 根据岗位id查询
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据岗位id查询
  /api/post/list:
    get:
      description: 分页查询岗位列表
      parameters:
      - description: 页码
        in: query
        name: pageNum
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        type: integer
      - description: 岗位名称
        in: query
        name: postName
        type: string
      - description: 岗位状态
        in: query
        name: pageStatus
        type: string
      - description: 开始时间
        in: query
        name: beginTime
        type: string
      - description: 结束时间
        in: query
        name: endTime
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 分页查询岗位列表
  /api/post/update:
    put:
      description: 编辑岗位
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysPost'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 编辑岗位
  /api/post/updateStatus:
    put:
      description: 岗位状态修改接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateSysPostStatusDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 岗位状态修改接口
  /api/post/vo/list:
    get:
      description: 岗位下拉列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 岗位下拉列表
  /api/role/add:
    post:
      description: 创建角色
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.AddSysRoleDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 创建角色
  /api/role/assignPermission:
    put:
      description: 分配权限
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.RoleMenu'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 分配权限
  /api/role/delete:
    delete:
      description: 删除角色
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.SysRoleIdDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 删除角色
  /api/role/info:
    get:
      description: 根据角色Id查询
      parameters:
      - description: Id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据角色Id查询
  /api/role/list:
    get:
      description: 获取角色列表(分页)
      parameters:
      - description: 页码
        in: query
        name: pageNum
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        type: integer
      - description: 角色名称
        in: query
        name: roleName
        type: string
      - description: 状态 ->启用 2->禁用
        in: query
        name: status
        type: string
      - description: 创建时间
        in: query
        name: beginTime
        type: string
      - description: 结束时间
        in: query
        name: endTime
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 获取角色列表(分页)
  /api/role/update:
    put:
      description: 编辑角色
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateSysRoleDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 编辑角色
  /api/role/updateStatus:
    put:
      description: 编辑角色状态
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateSysRoleStatusDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 编辑角色状态
  /api/role/vo/idList:
    get:
      description: 根据角色id查询菜单权限
      parameters:
      - description: Id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 根据角色id查询菜单权限
  /api/role/vo/list:
    get:
      description: 角色下拉列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Result'
      summary: 角色下拉列表
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
